"""empty message

Revision ID: 0470f415b8a2
Revises: a31e728864ea
Create Date: 2016-03-27 12:08:24.244278

"""

# revision identifiers, used by Alembic.
revision = '0470f415b8a2'
down_revision = 'a31e728864ea'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
