"""empty message

Revision ID: 08162c9ae60c
Revises: 1c57b69ef8ef
Create Date: 2016-03-21 11:26:44.986464

"""

# revision identifiers, used by Alembic.
revision = '08162c9ae60c'
down_revision = '1c57b69ef8ef'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
