"""empty message

Revision ID: 969995b9ddb7
Revises: d83b010e2b4e
Create Date: 2016-03-22 17:00:48.050992

"""

# revision identifiers, used by Alembic.
revision = '969995b9ddb7'
down_revision = 'd83b010e2b4e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
