"""empty message

Revision ID: a4696662e3cf
Revises: e4a2ca5ac8f3
Create Date: 2016-03-23 15:21:51.260835

"""

# revision identifiers, used by Alembic.
revision = 'a4696662e3cf'
down_revision = 'e4a2ca5ac8f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
