"""empty message

Revision ID: d83b010e2b4e
Revises: 04015f133b7a
Create Date: 2016-03-22 15:29:03.639218

"""

# revision identifiers, used by Alembic.
revision = 'd83b010e2b4e'
down_revision = '04015f133b7a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
