"""empty message

Revision ID: e4a2ca5ac8f3
Revises: 969995b9ddb7
Create Date: 2016-03-22 17:11:59.214771

"""

# revision identifiers, used by Alembic.
revision = 'e4a2ca5ac8f3'
down_revision = '969995b9ddb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
